import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import Chart from 'chart.js/auto'

import { Bar, Line, Scatter, Bubble} from 'react-chartjs-2'


const Home = () => {

  const lineData= {
    labels : ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
      {
        label : "Overview",
        data: [0.1, 0.4, 0.2, 0.3, 0.7, 0.4, 0.6, 0.3]
      }
    ]
  }

  const barData = {
    labels : ["January", "February", "March", "April", "May", "June", "July", "August", "September"],
    datasets: [
      {
        label : "Brut",
        borderRadius : 30,
        data: [0.1, 0.4, 0.2, 0.3, 0.7, 0.4, 0.6, 0.3, 0.4, 0.8],
        backgroundColor : "rgba(32, 214, 155, 1)",
        barThickness : 10
      },
      {
        label : "Net",
        borderRadius : 20,
        data: [0.07, 0.3, 0.15, 0.2, 0.5, 0.3, 0.8, 0.2, 0.4, 0.8],
        backgroundColor : "rgba(1, 98, 255, 1)",
        barThickness : 10
      }
    ]
  }

  const barOptions = {
    plugins : {
      legend : {
        position: "top",
        align: "start",
        display: true,
        labels : {
          boxWidth: 7,
          usePointStyle: true,
          pointStyle: "circle"
        },
        title : {
          text : "Sales Rport",
          display: true,
          color: "#00000",
          font : {
            size : 18
          }
        }
      }
    },
    scales: {
      xAxis : {
        display: true
      },
      yAxis : {
        display : true,
        max: 1,
      }
    },
    elements : {
      bar: {
        barPercentage : 0.3,
        categoryPercentage : 1
      }
    }
  }

  const lineOptions = {
    plugins : {
      legend : {
        display: true
      }
    },
    elements: {
      line:{
        tension: 0,
        borderWidth: 2,
        borderColor: "rgba(47,97,68,1)",
        fill: "start",
        backgroundColor: "rgba(47,97,68,.3)"
      },
      point:{
        radius: 0,
        hitRadius: 0
      }
    },
    scales: {
      xAxis : {
        display: true
      },
      yAxis : {
        display : true
      }
    }
  }

  console.log("You're on the landing page, Overview")

  return <div className={styles.container}>
    <Head>
      <title>Chart JS Discovery</title>
      <meta name="description" content="Chart Js discovery with NextJs. Generated by create next app" />
    </Head>
    <div className={styles.titleContainer}>
      <div className={styles.titleImage}>
        <Image
          src="/pictures/chartjs.png"
          alt="ChartJs Logo"
          layout="fill"
        />
      </div>
      <h1 className={styles.title}>Overview</h1>
    </div>
    <ul className={styles.chartContainer}>
      <li>
        <Line
          data={lineData}
          width={100}
          height={40}
          options={lineOptions}
        />
      </li>
      <li>
        <Bar 
          data={barData}
          height={300}
          options= {barOptions}
        />
      </li>
    </ul>
  </div>
}

export default Home
